### ISSUE TITLE
FTPS

### ISSUE THREAD

**Issue by crushedy** [SpotlightKid/micropython-ftplib#5]
Are you going to implement the FTPS or SFTP protocols?

**Comment by SpotlightKid** [comment]
SFTP: very unlikely, since this a completely different protocol to FTP.

FTP over TLS: maybe, but since I'm not using micropython very much anymore, I can't make any promises as to when. I'm open to consider a pull request, though, preferably with the implementation based on the `FTP_TLS` class in the CPython stdlib `ftplib.py`.

**Comment by SpotlightKid** [comment]
See #6 for adding FTP over TLS support.
